In [1]:
import pandas as pd
import os

In [2]:
SCRIPT_DIR_PATH = os.getcwd()
ROOT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
DATA_DIR_PATH = os.path.join(ROOT_DIR_PATH, "data")
MAPPING_DIR_PATH = os.path.join(DATA_DIR_PATH, "mapping")
PREDICTORS_DIR_PATH = os.path.join(DATA_DIR_PATH, "predictors")
SSP_DIR_PATH = os.path.join(DATA_DIR_PATH, "ssp")
SIMULATION_DIR_PATH = os.path.join(SSP_DIR_PATH, "sisepuede_run_2025-01-14T17;04;06.975301_output_database")
TRAINING_DIR_PATH = os.path.join(DATA_DIR_PATH, "training")

In [3]:
lhc_trials_df = pd.read_csv(os.path.join(PREDICTORS_DIR_PATH, "lhs_sample_group_experiments.csv"))
lhc_trials_df

,1,2,3,4,5,6,7,8,9,10,...,1472,1473,1474,1475,1476,1477,1478,1480,1481,future_id
0,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,0.490988,0.510280,...,0.985425,0.482783,0.183188,0.364889,0.005297,0.223598,0.927810,0.036368,0.933822,1
1,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,0.779857,0.623335,...,0.437877,0.149747,0.308130,0.780839,0.784662,0.742266,0.147130,0.081654,0.491202,2
2,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,0.884425,0.232722,...,0.360238,0.348950,0.165501,0.813845,0.950005,0.342632,0.053104,0.316417,0.173655,3
3,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,0.027114,0.532020,...,0.060470,0.660562,0.621883,0.911838,0.030974,0.912003,0.150989,0.246583,0.353195,4
4,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,0.346714,0.892123,...,0.910718,0.621574,0.244454,0.927056,0.561529,0.611280,0.552761,0.125694,0.147930,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,0.791412,0.300450,...,0.669261,0.883331,0.431040,0.045121,0.790492,0.081530,0.351688,0.746613,0.853002,996
996,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,0.657012,0.808412,...,0.538035,0.037013,0.528031,0.079728,0.918024,0.653280,0.161674,0.033243,0.257661,997
997,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,0.606286,0.678398,...,0.262631,0.657597,0.243538,0.603350,0.377625,0.316224,0.615736,0.996441,0.704642,998
998,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,0.009808,0.855097,...,0.069343,0.293393,0.632635,0.168413,0.611178,0.295950,0.813797,0.934377,0.473035,999
999,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,0.951080,0.509441,...,0.486452,0.115074,0.989445,0.965431,0.352193,0.278569,0.164544,0.144563,0.306248,1000

In [4]:
la_emissions_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "MODEL_OUTPUT.csv"))
la_emissions_df

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,yield_agrc_fruits_tonne,yield_agrc_herbs_and_other_perennial_crops_tonne,yield_agrc_nuts_tonne,yield_agrc_other_annual_tonne,yield_agrc_other_woody_perennial_tonne,yield_agrc_pulses_tonne,yield_agrc_rice_tonne,yield_agrc_sugar_cane_tonne,yield_agrc_tubers_tonne,yield_agrc_vegetables_and_vines_tonne
0,275275,louisiana,0,0.0,367983.831774,68239.857458,80.234375,79198.541655,6714.566582,1.154590e+06,...,1607.703461,955073.693482,19786.484805,7.132381e+06,0.0,985.642069,2.422231e+06,2.104457e+07,166526.651285,147.841681
1,275275,louisiana,1,0.0,362385.636787,67201.713944,79.013757,77993.681983,6612.416842,1.137025e+06,...,1618.201188,978025.173334,22849.096189,8.147695e+06,0.0,1148.204785,2.272766e+06,2.016430e+07,170339.476720,150.359797
2,275275,louisiana,2,0.0,361096.126663,66962.583908,78.732596,77716.149895,6588.887271,1.132979e+06,...,1574.244188,945124.232643,20042.187116,1.259799e+07,0.0,1389.455885,2.285081e+06,2.525521e+07,170252.877121,144.566821
3,275275,louisiana,3,0.0,359935.747562,66747.400257,78.479589,77466.409758,6567.713942,1.129338e+06,...,1487.104127,951997.620585,22167.895406,6.139224e+06,0.0,1457.885138,2.426876e+06,2.538268e+07,162040.494052,147.924261
4,275275,louisiana,4,0.0,358773.521179,66531.874041,78.226180,77216.272044,6546.506906,1.125692e+06,...,1583.188921,952671.199593,19588.348855,6.953864e+06,0.0,1125.040763,2.155513e+06,2.356779e+07,166703.308298,163.887648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36031,276275,louisiana,31,0.0,309402.632008,67494.007968,99.280790,89132.167800,16695.284559,1.161004e+06,...,1449.350481,871948.732854,12592.990056,7.021991e+06,0.0,1055.062331,2.276019e+06,2.403699e+07,196573.614611,166.806631
36032,276275,louisiana,32,0.0,309172.389911,68774.060665,102.272019,91149.219633,18708.483406,1.177036e+06,...,1477.427300,885367.523944,12723.047466,7.109925e+06,0.0,1059.561793,2.296005e+06,2.393306e+07,197056.903265,167.693033
36033,276275,louisiana,33,0.0,308983.403716,70116.106905,105.313909,93186.116688,21109.791025,1.193151e+06,...,1505.572198,898808.002401,12811.278216,7.198400e+06,0.0,1064.598028,2.315909e+06,2.383202e+07,197544.003011,168.591509
36034,276275,louisiana,34,0.0,308833.414335,71512.549952,108.393442,95232.747284,24019.931656,1.209256e+06,...,1533.599093,912175.594875,12844.529332,7.286867e+06,0.0,1070.123263,2.335624e+06,2.373561e+07,198045.569544,169.504094
36035,276275,louisiana,35,0.0,308715.398813,72954.834981,111.497279,97278.672613,27620.872881,1.225251e+06,...,1561.352004,925391.026439,12806.362698,7.374855e+06,0.0,1076.088767,2.355067e+06,2.364535e+07,198571.034958,170.432604

## Transform emissions time series data in target variables

In [5]:
subsector_totals_cols = [col for col in la_emissions_df.columns if "emission_co2e_subsector_total" in col]
subsector_totals_cols

['emission_co2e_subsector_total_agrc',
 'emission_co2e_subsector_total_ccsq',
 'emission_co2e_subsector_total_entc',
 'emission_co2e_subsector_total_fgtv',
 'emission_co2e_subsector_total_frst',
 'emission_co2e_subsector_total_inen',
 'emission_co2e_subsector_total_ippu',
 'emission_co2e_subsector_total_lndu',
 'emission_co2e_subsector_total_lsmm',
 'emission_co2e_subsector_total_lvst',
 'emission_co2e_subsector_total_scoe',
 'emission_co2e_subsector_total_soil',
 'emission_co2e_subsector_total_trns',
 'emission_co2e_subsector_total_trww',
 'emission_co2e_subsector_total_waso']

In [6]:
# Filter the la_emissions_df to only include the subsector totals
la_emissions_subsector_totals_df = la_emissions_df[["primary_id", "time_period"] + subsector_totals_cols]
la_emissions_subsector_totals_df.head()

,primary_id,time_period,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_ccsq,emission_co2e_subsector_total_entc,emission_co2e_subsector_total_fgtv,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
0,275275,0,1.584478,0.0,87.202869,13.785113,-25.538740,34.955562,92.323613,9.987402,0.284571,1.240654,5.408010,18.198756,43.813502,1.194832,1.799645
1,275275,1,1.573848,0.0,88.990055,13.574044,-26.918532,35.550361,117.400000,9.974551,0.282116,1.231179,4.777919,18.470387,41.755424,1.181568,1.769505
2,275275,2,1.667754,0.0,85.401680,12.342081,-20.181094,26.431299,70.076960,9.718344,0.282270,1.226150,4.587107,18.501348,42.378982,1.193562,1.793187
3,275275,3,1.557793,0.0,91.676280,13.536455,-13.789889,47.900892,122.294593,10.207034,0.283177,1.221255,4.909771,18.782501,44.782787,1.215421,1.837684
4,275275,4,1.538893,0.0,83.599591,12.560791,-39.346740,48.043708,124.008505,10.062773,0.284135,1.218990,4.955352,18.832322,45.549952,1.234366,1.862073

In [7]:
la_emissions_subsector_totals_df.describe()

,primary_id,time_period,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_ccsq,emission_co2e_subsector_total_entc,emission_co2e_subsector_total_fgtv,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
count,36036.000000,36036.000000,36036.000000,36036.000000,35568.000000,3.549600e+04,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000,36036.000000
mean,275775.000000,17.500000,1.494145,-5.704336,58.971131,1.640732e+05,-22.936383,22.374065,82.382937,9.075378,0.264578,1.116053,4.228966,17.291331,44.965940,1.376115,1.972730
std,288.967675,10.388439,0.108031,6.985615,19.666072,4.478756e+06,4.587002,11.493859,19.599622,1.342743,0.032315,0.124210,1.161032,1.728743,6.414301,0.177813,0.312887
min,275275.000000,0.000000,0.993046,-31.089497,0.000000,7.482932e-01,-39.346740,0.467359,15.125732,5.127605,0.096632,0.552511,0.000000,10.281916,14.842692,0.560147,0.576322
25%,275525.000000,8.750000,1.439667,-9.374685,42.297468,5.691094e+00,-24.638177,12.235994,69.799966,8.106246,0.251519,1.055924,3.638580,16.036658,42.268493,1.251804,1.833598
50%,275775.000000,17.500000,1.493822,-2.899111,60.477709,9.363813e+00,-22.036075,21.700643,83.822153,9.708261,0.282116,1.170415,4.638844,17.650062,45.939194,1.371728,1.986064
75%,276025.000000,26.250000,1.541257,0.000000,76.129367,1.234208e+01,-20.477532,31.889899,96.474084,10.159020,0.285308,1.203038,5.121714,18.832322,49.436358,1.456571,2.120570
max,276275.000000,35.000000,2.022461,0.000000,92.198674,1.732647e+08,-13.789889,48.043708,124.008505,11.593707,0.318353,1.330085,6.189927,19.784408,70.848398,2.236753,3.092847

In [8]:
# get the columns that have negative values
negative_cols = la_emissions_subsector_totals_df.columns[la_emissions_subsector_totals_df.min() < 0].to_list()
negative_cols

['emission_co2e_subsector_total_ccsq', 'emission_co2e_subsector_total_frst']

In [9]:
# Get the columns that have positive values only
positive_cols = la_emissions_subsector_totals_df.columns[la_emissions_subsector_totals_df.min() >= 0].to_list()
positive_cols.remove("primary_id")
positive_cols.remove("time_period")
positive_cols

['emission_co2e_subsector_total_agrc',
 'emission_co2e_subsector_total_entc',
 'emission_co2e_subsector_total_fgtv',
 'emission_co2e_subsector_total_inen',
 'emission_co2e_subsector_total_ippu',
 'emission_co2e_subsector_total_lndu',
 'emission_co2e_subsector_total_lsmm',
 'emission_co2e_subsector_total_lvst',
 'emission_co2e_subsector_total_scoe',
 'emission_co2e_subsector_total_soil',
 'emission_co2e_subsector_total_trns',
 'emission_co2e_subsector_total_trww',
 'emission_co2e_subsector_total_waso']

In [10]:
la_emissions_subsector_totals_df.loc[:, "total_positive_emissions"] = la_emissions_subsector_totals_df[positive_cols].sum(axis=1)
la_emissions_subsector_totals_df.loc[:, "total_negative_emissions"] = la_emissions_subsector_totals_df[negative_cols].sum(axis=1)

/tmp/ipykernel_63337/461548257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  la_emissions_subsector_totals_df.loc[:, "total_positive_emissions"] = la_emissions_subsector_totals_df[positive_cols].sum(axis=1)
/tmp/ipykernel_63337/461548257.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  la_emissions_subsector_totals_df.loc[:, "total_negative_emissions"] = la_emissions_subsector_totals_df[negative_cols].sum(axis=1)

In [11]:
la_emissions_subsector_totals_df = la_emissions_subsector_totals_df[["primary_id", "time_period", "total_positive_emissions", "total_negative_emissions"]]
la_emissions_subsector_totals_df.head()

   primary_id  time_period  total_positive_emissions  total_negative_emissions
0      275275            0                311.779006                -25.538740
1      275275            1                336.530958                -26.918532
2      275275            2                275.600725                -20.181094
3      275275            3                360.205642                -13.789889
4      275275            4                353.751451                -39.346740

In [12]:
# Filter out rows with time_period <= 30
la_emissions_subsector_totals_df = la_emissions_subsector_totals_df[la_emissions_subsector_totals_df["time_period"] > 30]
la_emissions_subsector_totals_df.head(7)

,primary_id,time_period,total_positive_emissions,total_negative_emissions
31,275275,31,87.843667,-46.178550
32,275275,32,82.560802,-47.680408
33,275275,33,77.375053,-49.206904
34,275275,34,71.892013,-50.753650
35,275275,35,66.727573,-52.314258
67,275276,31,187.836673,-44.059580
68,275276,32,184.114221,-45.247118

In [13]:
# aggregate data by primary_id and region by summing the emissions
la_emissions_df_agg = la_emissions_subsector_totals_df.groupby(["primary_id"]).sum().reset_index()
la_emissions_df_agg

,primary_id,time_period,total_positive_emissions,total_negative_emissions
0,275275,165,386.399108,-246.133770
1,275276,165,902.639418,-232.131775
2,275277,165,724.378452,-119.927915
3,275278,165,704.191065,-228.482434
4,275279,165,947.002903,-188.998568
...,...,...,...,...
996,276271,165,838.294268,-214.955628
997,276272,165,1017.110137,-269.751464
998,276273,165,851.262402,-217.108265
999,276274,165,1076.501959,-160.784180
1000,276275,165,884.878769,-209.792342

In [14]:
# Drop time period column as it is no longer needed
la_emissions_df_agg = la_emissions_df_agg.drop(columns=["time_period"], errors='ignore')
la_emissions_df_agg.describe()

          primary_id  total_positive_emissions  total_negative_emissions
count    1001.000000              1.001000e+03               1001.000000
mean   275775.000000              7.685265e+05               -198.732289
std       289.108111              1.071140e+07                 39.675362
min    275275.000000              3.863991e+02               -287.044374
25%    275525.000000              8.321846e+02               -231.424917
50%    275775.000000              9.174224e+02               -196.439322
75%    276025.000000              9.982849e+02               -168.690833
max    276275.000000              2.268720e+08               -111.063472

## Merge emissions data with lhs samples

In [15]:
attr_primary_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "ATTRIBUTE_PRIMARY.csv"))
attr_primary_df

      primary_id  design_id  strategy_id  future_id
0         275275          3         6002          0
1         275276          3         6002          1
2         275277          3         6002          2
3         275278          3         6002          3
4         275279          3         6002          4
...          ...        ...          ...        ...
996       276271          3         6002        996
997       276272          3         6002        997
998       276273          3         6002        998
999       276274          3         6002        999
1000      276275          3         6002       1000

[1001 rows x 4 columns]

In [17]:
la_emissions_df_w_future_id = la_emissions_df_agg.merge(attr_primary_df, on="primary_id", how="inner")

# Drop design_id and stratgy_id columns
la_emissions_df_w_future_id = la_emissions_df_w_future_id.drop(columns=["design_id", "strategy_id"])
la_emissions_df_w_future_id

,primary_id,total_positive_emissions,total_negative_emissions,future_id
0,275275,386.399108,-246.133770,0
1,275276,902.639418,-232.131775,1
2,275277,724.378452,-119.927915,2
3,275278,704.191065,-228.482434,3
4,275279,947.002903,-188.998568,4
...,...,...,...,...
996,276271,838.294268,-214.955628,996
997,276272,1017.110137,-269.751464,997
998,276273,851.262402,-217.108265,998
999,276274,1076.501959,-160.784180,999
1000,276275,884.878769,-209.792342,1000

In [18]:
merged_df = pd.merge(lhc_trials_df, la_emissions_df_w_future_id, on="future_id", how="inner")

# rearrange columns to have future_id and primary_id at the front
cols_order = ["future_id", "primary_id"] + [col for col in merged_df.columns if col not in ["future_id", "primary_id"]]
merged_df = merged_df[cols_order]
merged_df

,future_id,primary_id,1,2,3,4,5,6,7,8,...,1473,1474,1475,1476,1477,1478,1480,1481,total_positive_emissions,total_negative_emissions
0,1,275276,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,...,0.482783,0.183188,0.364889,0.005297,0.223598,0.927810,0.036368,0.933822,902.639418,-232.131775
1,2,275277,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,...,0.149747,0.308130,0.780839,0.784662,0.742266,0.147130,0.081654,0.491202,724.378452,-119.927915
2,3,275278,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,...,0.348950,0.165501,0.813845,0.950005,0.342632,0.053104,0.316417,0.173655,704.191065,-228.482434
3,4,275279,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,...,0.660562,0.621883,0.911838,0.030974,0.912003,0.150989,0.246583,0.353195,947.002903,-188.998568
4,5,275280,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,...,0.621574,0.244454,0.927056,0.561529,0.611280,0.552761,0.125694,0.147930,833.854631,-233.083200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,276271,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,...,0.883331,0.431040,0.045121,0.790492,0.081530,0.351688,0.746613,0.853002,838.294268,-214.955628
996,997,276272,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,...,0.037013,0.528031,0.079728,0.918024,0.653280,0.161674,0.033243,0.257661,1017.110137,-269.751464
997,998,276273,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,...,0.657597,0.243538,0.603350,0.377625,0.316224,0.615736,0.996441,0.704642,851.262402,-217.108265
998,999,276274,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,...,0.293393,0.632635,0.168413,0.611178,0.295950,0.813797,0.934377,0.473035,1076.501959,-160.784180
999,1000,276275,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,...,0.115074,0.989445,0.965431,0.352193,0.278569,0.164544,0.144563,0.306248,884.878769,-209.792342

In [19]:
var_traj_df = pd.read_csv(os.path.join(MAPPING_DIR_PATH, "var_trajgroups_experiment.csv"))
var_traj_df.tail(10)

    variable_trajectory_group
37                         38
38                         39
39                         40
40                         41
41                         42
42                         43
43                         44
44                         45
45                         46
46                         47

In [20]:
# Convert the variable_trajectory_group column to list of strings
relevant_lhs_cols = var_traj_df["variable_trajectory_group"].values
relevant_lhs_cols = [str(col) for col in relevant_lhs_cols.tolist()]
# relevant_lhs_cols

In [21]:
df_cols = merged_df.columns.tolist()

# Filter the relevant_lhs_cols to only include those that are in df_cols
relevant_lhs_cols = [col for col in relevant_lhs_cols if col in df_cols]

In [23]:
# filter merged_df to keep only relevant columns
cols_to_keep = ["future_id", "primary_id"] + list(relevant_lhs_cols) + ["total_positive_emissions", "total_negative_emissions"]
merged_df_filtered = merged_df[cols_to_keep]

In [24]:
merged_df_filtered

,future_id,primary_id,1,2,3,4,5,6,7,8,...,40,41,42,43,44,45,46,47,total_positive_emissions,total_negative_emissions
0,1,275276,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,...,0.289038,0.996557,0.053597,0.175103,0.379422,0.438093,0.149362,0.869757,902.639418,-232.131775
1,2,275277,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,...,0.536533,0.385371,0.246165,0.101025,0.717013,0.368791,0.774941,0.483352,724.378452,-119.927915
2,3,275278,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,...,0.533412,0.601590,0.122444,0.653845,0.216259,0.714853,0.881270,0.581230,704.191065,-228.482434
3,4,275279,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,...,0.264120,0.938985,0.592915,0.564895,0.027725,0.138890,0.820709,0.250616,947.002903,-188.998568
4,5,275280,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,...,0.430582,0.492564,0.432240,0.662820,0.179231,0.631375,0.395960,0.661637,833.854631,-233.083200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,276271,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,...,0.004788,0.319760,0.567859,0.873065,0.309462,0.213959,0.531121,0.413153,838.294268,-214.955628
996,997,276272,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,...,0.695228,0.368169,0.356410,0.584330,0.195851,0.217361,0.920388,0.402516,1017.110137,-269.751464
997,998,276273,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,...,0.326525,0.828078,0.653782,0.429175,0.977175,0.914779,0.307569,0.506892,851.262402,-217.108265
998,999,276274,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,...,0.398381,0.757483,0.826523,0.961181,0.882943,0.900195,0.448056,0.664405,1076.501959,-160.784180
999,1000,276275,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,...,0.389584,0.300123,0.936939,0.657785,0.017582,0.513939,0.232670,0.118241,884.878769,-209.792342

## Add variable names to lhs columns

In [25]:
var_specifications_df = pd.read_csv(os.path.join(MAPPING_DIR_PATH, "variable_specification_to_sample_group.csv"))
# Filter var_specifications_df by sample_group in relevant_lhs_cols
relevant_lhs_cols = [int(col) for col in relevant_lhs_cols]
var_specifications_df = var_specifications_df[var_specifications_df["sample_group"].isin(relevant_lhs_cols)]
var_specifications_df = var_specifications_df.sort_values(by="sample_group", ascending=True)

In [26]:
def process_variable_prefix(df):
    result = []
    for group, group_df in df.groupby('sample_group'):
        variables = group_df['variable_specification'].tolist()
        if len(variables) == 1:
            prefix = variables[0]
        else:
            prefix = os.path.commonprefix(variables)
            # Clean trailing underscores
            prefix = prefix.rstrip('_')
            
        prefix = f"group_{group}_{prefix}"
        result.append({'sample_group': group, 'variable_prefix': prefix})
    return pd.DataFrame(result)

prefix_df = process_variable_prefix(var_specifications_df)
prefix_df

    sample_group                                    variable_prefix
0              1                            group_1_ef_lvst_entferm
1              2                                    group_2_yf_agrc
2              3                             group_3_demscalar_soil
3              4                             group_4_demscalar_ippu
4              5    group_5_efficfactor_enfu_industrial_energy_fuel
5              6                    group_6_elecfuelefficiency_trns
6              7   group_7_factor_waso_waste_per_capita_scalar_food
7              8                                  group_8_frac_fgtv
8              9      group_9_frac_agrc_agriculture_production_lost
9             10                                 group_10_frac_agrc
10            12  group_12_frac_enfu_transmission_loss_fuel_elec...
11            13                                          group_13_
12            14                  group_14_frac_ippu_cement_clinker
13            15     group_15_frac_ippu_production_with_co2_capture
14            16                              group_16_frac_lvst_mm
15            17                         group_17_frac_trns_fuelmix
16            18                group_18_frac_trns_mtkm_dem_freight
17            19                         group_19_frac_trns_pkm_dem
18            20                              group_20_frac_wali_ww
19            21                    group_21_frac_waso_non_recycled
20            22                                 group_22_frac_waso
21            23                        group_23_frac_waso_recycled
22            24                                 group_24_frac_waso
23            25                          group_25_frac_inen_energy
24            26                          group_26_frac_inen_energy
25            27                     group_27_frac_scoe_heat_energy
26            28                       group_28_fuelefficiency_trns
27            29                                     group_29_gasrf
28            30                             group_30_ef_ippu_tonne
29            31                     group_31_ef_ippu_tonne_n2o_per
30            32                  group_32_lndu_reallocation_factor
31            33                              group_33_exports_lvst
32            34                                group_34_nemomod_en
33            35  group_35_occrate_trns_passenger_per_vehicle_ro...
34            36                     group_36_pij_lndu_croplands_to
35            37             group_37_pij_lndu_forests_mangroves_to
36            38               group_38_pij_lndu_forests_primary_to
37            39             group_39_pij_lndu_forests_secondary_to
38            40                                          group_40_
39            41                         group_41_pij_lndu_other_to
40            42                   group_42_pij_lndu_settlements_to
41            43                      group_43_pij_lndu_wetlands_to
42            44       group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha
43            45             group_45_scalar_lvst_carrying_capacity
44            46       group_46_scalar_scoe_appliance_energy_demand
45            47            group_47_scalar_scoe_heat_energy_demand

In [27]:
var_specifications_df[var_specifications_df["sample_group"].isin([13, 40])]

                           variable_specification  sample_group
560   elasticity_agrc_sugar_cane_demand_to_income            13
876                     frac_gnrl_eating_red_meat            13
1177      frac_lndu_proportion_grasslands_pasture            40
2020       pij_lndu_grasslands_to_forests_primary            40
2021     pij_lndu_grasslands_to_forests_secondary            40
2022            pij_lndu_grasslands_to_grasslands            40
2024           pij_lndu_grasslands_to_settlements            40
2025              pij_lndu_grasslands_to_wetlands            40
2023                 pij_lndu_grasslands_to_other            40
2019     pij_lndu_grasslands_to_forests_mangroves            40
2018             pij_lndu_grasslands_to_croplands            40

In [28]:
prefix_df.loc[prefix_df["sample_group"] == 13, "variable_prefix"] = "group_13_frac_gnrl_eating_red_meats+"
prefix_df.loc[prefix_df["sample_group"] == 40, "variable_prefix"] = "group_40_pij_lndu_grasslands+"

prefix_df = prefix_df.sort_values(by="variable_prefix", ascending=True)
prefix_df

    sample_group                                    variable_prefix
9             10                                 group_10_frac_agrc
10            12  group_12_frac_enfu_transmission_loss_fuel_elec...
11            13               group_13_frac_gnrl_eating_red_meats+
12            14                  group_14_frac_ippu_cement_clinker
13            15     group_15_frac_ippu_production_with_co2_capture
14            16                              group_16_frac_lvst_mm
15            17                         group_17_frac_trns_fuelmix
16            18                group_18_frac_trns_mtkm_dem_freight
17            19                         group_19_frac_trns_pkm_dem
0              1                            group_1_ef_lvst_entferm
18            20                              group_20_frac_wali_ww
19            21                    group_21_frac_waso_non_recycled
20            22                                 group_22_frac_waso
21            23                        group_23_frac_waso_recycled
22            24                                 group_24_frac_waso
23            25                          group_25_frac_inen_energy
24            26                          group_26_frac_inen_energy
25            27                     group_27_frac_scoe_heat_energy
26            28                       group_28_fuelefficiency_trns
27            29                                     group_29_gasrf
1              2                                    group_2_yf_agrc
28            30                             group_30_ef_ippu_tonne
29            31                     group_31_ef_ippu_tonne_n2o_per
30            32                  group_32_lndu_reallocation_factor
31            33                              group_33_exports_lvst
32            34                                group_34_nemomod_en
33            35  group_35_occrate_trns_passenger_per_vehicle_ro...
34            36                     group_36_pij_lndu_croplands_to
35            37             group_37_pij_lndu_forests_mangroves_to
36            38               group_38_pij_lndu_forests_primary_to
37            39             group_39_pij_lndu_forests_secondary_to
2              3                             group_3_demscalar_soil
38            40                      group_40_pij_lndu_grasslands+
39            41                         group_41_pij_lndu_other_to
40            42                   group_42_pij_lndu_settlements_to
41            43                      group_43_pij_lndu_wetlands_to
42            44       group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha
43            45             group_45_scalar_lvst_carrying_capacity
44            46       group_46_scalar_scoe_appliance_energy_demand
45            47            group_47_scalar_scoe_heat_energy_demand
3              4                             group_4_demscalar_ippu
4              5    group_5_efficfactor_enfu_industrial_energy_fuel
5              6                    group_6_elecfuelefficiency_trns
6              7   group_7_factor_waso_waste_per_capita_scalar_food
7              8                                  group_8_frac_fgtv
8              9      group_9_frac_agrc_agriculture_production_lost

In [29]:
# Let's use the prefix_df to rename the columns in merged_df_filtered
def rename_columns_with_prefix(merged_df, prefix_df):
    df = merged_df.copy()
    for _, row in prefix_df.iterrows():
        sample_group = row['sample_group']
        variable_prefix = row['variable_prefix']
        cols_to_rename = [col for col in df.columns if col.startswith(str(sample_group))]
        for col in cols_to_rename:
            new_col_name = f"{variable_prefix}"
            df = df.rename(columns={col: new_col_name})
    return df
merged_df_filtered_w_prefix = rename_columns_with_prefix(merged_df_filtered, prefix_df)

In [30]:
merged_df_filtered_w_prefix

,future_id,primary_id,group_1_ef_lvst_entferm,group_2_yf_agrc,group_3_demscalar_soil,group_4_demscalar_ippu,group_5_efficfactor_enfu_industrial_energy_fuel,group_6_elecfuelefficiency_trns,group_7_factor_waso_waste_per_capita_scalar_food,group_8_frac_fgtv,...,group_40_pij_lndu_grasslands+,group_41_pij_lndu_other_to,group_42_pij_lndu_settlements_to,group_43_pij_lndu_wetlands_to,group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha,group_45_scalar_lvst_carrying_capacity,group_46_scalar_scoe_appliance_energy_demand,group_47_scalar_scoe_heat_energy_demand,total_positive_emissions,total_negative_emissions
0,1,275276,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,...,0.289038,0.996557,0.053597,0.175103,0.379422,0.438093,0.149362,0.869757,902.639418,-232.131775
1,2,275277,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,...,0.536533,0.385371,0.246165,0.101025,0.717013,0.368791,0.774941,0.483352,724.378452,-119.927915
2,3,275278,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,...,0.533412,0.601590,0.122444,0.653845,0.216259,0.714853,0.881270,0.581230,704.191065,-228.482434
3,4,275279,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,...,0.264120,0.938985,0.592915,0.564895,0.027725,0.138890,0.820709,0.250616,947.002903,-188.998568
4,5,275280,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,...,0.430582,0.492564,0.432240,0.662820,0.179231,0.631375,0.395960,0.661637,833.854631,-233.083200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,276271,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,...,0.004788,0.319760,0.567859,0.873065,0.309462,0.213959,0.531121,0.413153,838.294268,-214.955628
996,997,276272,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,...,0.695228,0.368169,0.356410,0.584330,0.195851,0.217361,0.920388,0.402516,1017.110137,-269.751464
997,998,276273,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,...,0.326525,0.828078,0.653782,0.429175,0.977175,0.914779,0.307569,0.506892,851.262402,-217.108265
998,999,276274,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,...,0.398381,0.757483,0.826523,0.961181,0.882943,0.900195,0.448056,0.664405,1076.501959,-160.784180
999,1000,276275,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,...,0.389584,0.300123,0.936939,0.657785,0.017582,0.513939,0.232670,0.118241,884.878769,-209.792342

In [31]:
#save the merged DataFrame to a CSV file
merged_df_filtered_w_prefix.to_csv(os.path.join(TRAINING_DIR_PATH, "training_data_v2.csv"), index=False)