In [1]:
import pandas as pd
import os
from utils.eda_utils import EDAUtils
import boto3

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
SCRIPT_DIR_PATH = os.getcwd()
ROOT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
DATA_DIR_PATH = os.path.join(ROOT_DIR_PATH, "data")
MAPPING_DIR_PATH = os.path.join(DATA_DIR_PATH, "mapping")
SSP_DIR_PATH = os.path.join(DATA_DIR_PATH, "ssp")
TRAINING_DIR_PATH = os.path.join(DATA_DIR_PATH, "training")
CONFIG_DIR_PATH = os.path.join(ROOT_DIR_PATH, "config")

In [4]:
os.makedirs(SSP_DIR_PATH, exist_ok=True)

In [5]:
edau = EDAUtils()

## Pull SSP run from AWS S3 and load other important files

In [ ]:
aws_config = edau.read_yaml(os.path.join(CONFIG_DIR_PATH, "aws_credentials_config.yaml"))
profile_name = aws_config["profile_name"]
bucket_name = aws_config["bucket_name"]
# Set your profile
session = boto3.Session(profile_name=profile_name)

# Create an S3 client or resource
s3 = session.resource('s3')

# Define folder prefix
prefix = 'sisepuede_run_2025-01-14T17;04;06.975301_output_database/'  # this is like the "folder" in S3

In [ ]:
# Local destination
destination = os.path.join(SSP_DIR_PATH, prefix.strip('/'))
if os.path.exists(destination) and os.listdir(destination):
    print(f"Destination '{destination}' already exists and is not empty. Skipping download.")
else:
    os.makedirs(destination, exist_ok=True)
    bucket = s3.Bucket(bucket_name)
    for obj in bucket.objects.filter(Prefix=prefix):
        if obj.key.endswith('/'):  # skip directories
            continue
        target_path = os.path.join(destination, os.path.basename(obj.key))
        bucket.download_file(obj.key, target_path)
        print(f"Downloaded: {obj.key}")

In [6]:
# Define folder prefix
prefix = 'sisepuede_run_2025-01-14T17;04;06.975301_output_database/'  # this is like the "folder" in S3

In [7]:
SIMULATION_DIR_PATH = os.path.join(SSP_DIR_PATH, prefix.strip('/'))

In [8]:
lhs_trials_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "lhs_sample_group_experiments.csv"))
lhs_trials_df

,1,2,3,4,5,6,7,8,9,10,...,1472,1473,1474,1475,1476,1477,1478,1480,1481,future_id
0,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,0.490988,0.510280,...,0.985425,0.482783,0.183188,0.364889,0.005297,0.223598,0.927810,0.036368,0.933822,1
1,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,0.779857,0.623335,...,0.437877,0.149747,0.308130,0.780839,0.784662,0.742266,0.147130,0.081654,0.491202,2
2,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,0.884425,0.232722,...,0.360238,0.348950,0.165501,0.813845,0.950005,0.342632,0.053104,0.316417,0.173655,3
3,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,0.027114,0.532020,...,0.060470,0.660562,0.621883,0.911838,0.030974,0.912003,0.150989,0.246583,0.353195,4
4,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,0.346714,0.892123,...,0.910718,0.621574,0.244454,0.927056,0.561529,0.611280,0.552761,0.125694,0.147930,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,0.791412,0.300450,...,0.669261,0.883331,0.431040,0.045121,0.790492,0.081530,0.351688,0.746613,0.853002,996
996,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,0.657012,0.808412,...,0.538035,0.037013,0.528031,0.079728,0.918024,0.653280,0.161674,0.033243,0.257661,997
997,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,0.606286,0.678398,...,0.262631,0.657597,0.243538,0.603350,0.377625,0.316224,0.615736,0.996441,0.704642,998
998,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,0.009808,0.855097,...,0.069343,0.293393,0.632635,0.168413,0.611178,0.295950,0.813797,0.934377,0.473035,999
999,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,0.951080,0.509441,...,0.486452,0.115074,0.989445,0.965431,0.352193,0.278569,0.164544,0.144563,0.306248,1000

In [9]:
lhs_trials_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 85 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   1          1000 non-null   float64
 1   2          1000 non-null   float64
 2   3          1000 non-null   float64
 3   4          1000 non-null   float64
 4   5          1000 non-null   float64
 5   6          1000 non-null   float64
 6   7          1000 non-null   float64
 7   8          1000 non-null   float64
 8   9          1000 non-null   float64
 9   10         1000 non-null   float64
 10  12         1000 non-null   float64
 11  13         1000 non-null   float64
 12  14         1000 non-null   float64
 13  15         1000 non-null   float64
 14  16         1000 non-null   float64
 15  17         1000 non-null   float64
 16  18         1000 non-null   float64
 17  19         1000 non-null   float64
 18  20         1000 non-null   float64
 19  21         1000 non-null   float64
 20  22         1000 non-null   float64
 21  23         1000 non-null   float64
 22  24         1000 non-null   float64
 23  25         1000 non-null   float64
 24  26         1000 non-null   float64
 25  27         1000 non-null   float64
 26  28         1000 non-null   float64
 27  29         1000 non-null   float64
 28  30         1000 non-null   float64
 29  31         1000 non-null   float64
 30  32         1000 non-null   float64
 31  33         1000 non-null   float64
 32  34         1000 non-null   float64
 33  35         1000 non-null   float64
 34  36         1000 non-null   float64
 35  37         1000 non-null   float64
 36  38         1000 non-null   float64
 37  39         1000 non-null   float64
 38  40         1000 non-null   float64
 39  41         1000 non-null   float64
 40  42         1000 non-null   float64
 41  43         1000 non-null   float64
 42  44         1000 non-null   float64
 43  45         1000 non-null   float64
 44  46         1000 non-null   float64
 45  47         1000 non-null   float64
 46  114        1000 non-null   float64
 47  115        1000 non-null   float64
 48  116        1000 non-null   float64
 49  251        1000 non-null   float64
 50  252        1000 non-null   float64
 51  262        1000 non-null   float64
 52  263        1000 non-null   float64
 53  265        1000 non-null   float64
 54  279        1000 non-null   float64
 55  280        1000 non-null   float64
 56  281        1000 non-null   float64
 57  802        1000 non-null   float64
 58  803        1000 non-null   float64
 59  827        1000 non-null   float64
 60  893        1000 non-null   float64
 61  1384       1000 non-null   float64
 62  1459       1000 non-null   float64
 63  1460       1000 non-null   float64
 64  1461       1000 non-null   float64
 65  1462       1000 non-null   float64
 66  1463       1000 non-null   float64
 67  1464       1000 non-null   float64
 68  1465       1000 non-null   float64
 69  1466       1000 non-null   float64
 70  1467       1000 non-null   float64
 71  1468       1000 non-null   float64
 72  1469       1000 non-null   float64
 73  1470       1000 non-null   float64
 74  1471       1000 non-null   float64
 75  1472       1000 non-null   float64
 76  1473       1000 non-null   float64
 77  1474       1000 non-null   float64
 78  1475       1000 non-null   float64
 79  1476       1000 non-null   float64
 80  1477       1000 non-null   float64
 81  1478       1000 non-null   float64
 82  1480       1000 non-null   float64
 83  1481       1000 non-null   float64
 84  future_id  1000 non-null   int64
dtypes: float64(84), int64(1)
memory usage: 664.2 KB

In [10]:
wide_inputs_outputs_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "WIDE_INPUTS_OUTPUTS.csv"))
wide_inputs_outputs_df

,primary_id,region,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,...,yf_agrc_fruits_tonne_ha,yf_agrc_herbs_and_other_perennial_crops_tonne_ha,yf_agrc_nuts_tonne_ha,yf_agrc_other_annual_tonne_ha,yf_agrc_other_woody_perennial_tonne_ha,yf_agrc_pulses_tonne_ha,yf_agrc_rice_tonne_ha,yf_agrc_sugar_cane_tonne_ha,yf_agrc_tubers_tonne_ha,yf_agrc_vegetables_and_vines_tonne_ha
0,275275,louisiana,7,0,352056.299497,65286.215373,76.761572,75770.572219,6423.938390,1.104616e+06,...,18.989020,11.831723,2.782454,6.177415,0,3.474771,8.253027,87.719298,41.144328,31.476288
1,275275,louisiana,8,0,349848.854439,64876.861148,76.280265,75295.479526,6383.659346,1.097689e+06,...,18.791974,11.736001,2.699011,5.189029,0,2.688411,8.475414,83.271559,41.748977,31.761360
2,275275,louisiana,9,0,347657.028850,64470.403437,75.802365,74823.748501,6343.665309,1.090812e+06,...,18.594927,11.640280,2.615567,6.319971,0,3.416092,8.422668,89.334930,42.353627,32.046432
3,275275,louisiana,10,0,345480.707102,64066.820799,75.327844,74355.354257,6303.954170,1.083984e+06,...,18.397880,11.544559,2.532124,6.299606,0,3.415907,8.422736,90.402061,42.958276,32.331504
4,275275,louisiana,11,0,343319.774453,63666.091953,74.856679,73890.272100,6264.523834,1.077204e+06,...,18.200833,11.448838,2.448681,6.279241,0,3.415722,8.422804,91.469193,43.562926,32.616576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28560,275293,louisiana,31,0,294221.428184,63220.177553,89.937159,81027.978802,16195.145410,1.078609e+06,...,15.352838,10.364332,0.639586,6.489255,0,3.802796,9.390390,128.685483,63.702379,43.496713
28561,275293,louisiana,32,0,292599.377554,63909.784176,92.081486,82305.169476,17949.679259,1.087869e+06,...,15.332242,10.370063,0.599125,6.513671,0,3.823289,9.441271,129.944000,64.365588,43.882292
28562,275293,louisiana,33,0,291148.417580,64642.940250,94.277370,83613.385961,19878.507594,1.097669e+06,...,15.323540,10.381572,0.563700,6.539317,0,3.843794,9.492147,131.138110,64.992304,44.250665
28563,275293,louisiana,34,0,289866.317272,65408.965880,96.504382,84938.693208,21970.474633,1.107899e+06,...,15.326730,10.398858,0.533311,6.566192,0,3.864310,9.543020,132.267813,65.582526,44.601833
28564,275293,louisiana,35,0,288750.123258,66197.018891,98.742234,86267.472804,24204.753673,1.118450e+06,...,15.341813,10.421921,0.507959,6.594296,0,3.884837,9.593889,133.333109,66.136254,44.935795

In [11]:
cb_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "wide_cb_data_lhc1000_2025_06_27.csv"))
cb_df.head()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,275275,0,PFLO:ALL,2022,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.000000
1,275275,0,PFLO:ALL,2023,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.000000
2,275275,0,PFLO:ALL,2024,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.0,0.000000,0.000000,0.000000
3,275275,0,PFLO:ALL,2025,0.205981,1.121264e-18,0.019762,2.258582e-14,-2.697925e-15,0.0,...,0.019772,0.0,-0.002262,0.000012,1.586989e-18,-151886.454973,0.0,1.582723,0.399550,-0.000002
4,275275,0,PFLO:ALL,2026,0.208454,5.387895e-19,0.041808,1.321213e-14,-8.117058e-15,0.0,...,0.039802,0.0,-0.002248,0.000013,9.260588e-19,-147526.882403,0.0,8.884747,0.402695,-0.000002

In [12]:
good_cols = cb_df.columns[cb_df.notna().all()]
df_no_nas = cb_df[good_cols]
for col in df_no_nas:
    print(col)

primary_id
future_id
strategy_code
Year
consumer_savings
human_health
technical_cost

In [ ]:
cb_df['primary_id'].unique()

In [ ]:
cb_df[cb_df["primary_id"]==276254]

In [13]:
cb_df.tail()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
28560,276275,1000,PFLO:ALL,2046,NaN,NaN,0.558054,NaN,NaN,NaN,...,0.483845,NaN,NaN,NaN,NaN,NaN,NaN,-0.616939,NaN,NaN
28561,276275,1000,PFLO:ALL,2047,NaN,NaN,0.585593,NaN,NaN,NaN,...,0.507830,NaN,NaN,NaN,NaN,NaN,NaN,-0.649769,NaN,NaN
28562,276275,1000,PFLO:ALL,2048,NaN,NaN,0.613291,NaN,NaN,NaN,...,0.531981,NaN,NaN,NaN,NaN,NaN,NaN,-0.683128,NaN,NaN
28563,276275,1000,PFLO:ALL,2049,NaN,NaN,0.641153,NaN,NaN,NaN,...,0.556302,NaN,NaN,NaN,NaN,NaN,NaN,-0.717001,NaN,NaN
28564,276275,1000,PFLO:ALL,2050,NaN,NaN,0.669185,NaN,NaN,NaN,...,0.580799,NaN,NaN,NaN,NaN,NaN,NaN,-0.751297,NaN,NaN

In [14]:
for col in cb_df.columns:
    print(col)

primary_id
future_id
strategy_code
Year
air_pollution
congestion
consumer_savings
crop_value
ecosystem_services
env_pollution
fuel_cost
human_health
ippu_value
land_pollution
lvst_value
road_safety
sector_specific
system_cost
technical_cost
technical_savings
water_pollution

## Data Cleaning

### Emission data

In [15]:
# Get the subsector total variables
subsector_total_vars = [c for c in wide_inputs_outputs_df.columns if "emission_co2e_subsector_total" in c]

In [16]:
# Filter to only emission columns avoiding "subsector" total columns
la_emissions_df = wide_inputs_outputs_df[["primary_id", "time_period"] + subsector_total_vars]
la_emissions_df.head()

,primary_id,time_period,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_ccsq,emission_co2e_subsector_total_entc,emission_co2e_subsector_total_fgtv,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
0,275275,7,2.923974,0.0,30.469259,13.094104,-36.545088,117.042622,2.629950,2.050000,0.230319,1.539811,4.491483,1.233181,45.130223,0.447204,3.138402
1,275275,8,2.857986,0.0,28.476065,11.929561,-38.817968,114.193574,2.640618,2.057088,0.230824,1.533068,4.525427,1.242080,45.862823,0.454013,3.187628
2,275275,9,2.899699,0.0,34.882828,15.633156,-40.622482,113.969034,2.653297,2.064100,0.231385,1.526359,4.561015,1.247478,46.693347,0.461144,3.238212
3,275275,10,2.882666,0.0,35.016651,15.680324,-42.118513,112.576725,2.667916,2.071038,0.231985,1.519683,4.598400,1.249169,47.602613,0.468528,3.289838
4,275275,11,2.865747,0.0,35.168961,15.736519,-43.406884,111.119217,2.684396,2.077902,0.232615,1.513040,4.637649,1.247322,48.575658,0.476114,3.342286

In [17]:
la_emissions_df.tail()

,primary_id,time_period,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_ccsq,emission_co2e_subsector_total_entc,emission_co2e_subsector_total_fgtv,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso
28560,275293,31,2.110364,-13.766029,31.289049,11.000474,-44.540430,32.319108,1.643350,1.479102,0.142339,1.055245,2.497746,0.852071,34.372764,0.480754,4.822194
28561,275293,32,2.083985,-14.490557,32.105438,11.007629,-44.529357,30.167919,1.593072,1.493447,0.136690,1.034212,2.398251,0.848281,33.848357,0.476335,4.874980
28562,275293,33,2.058421,-15.215085,32.915276,11.028479,-44.512595,28.134717,1.542679,1.506934,0.130917,1.012776,2.299644,0.846124,33.326949,0.471336,4.924921
28563,275293,34,2.033523,-15.939613,33.739602,11.044059,-44.488490,26.216735,1.492082,1.519494,0.125031,0.991002,2.201758,0.844632,32.805388,0.465727,4.971923
28564,275293,35,2.009155,-16.664141,34.574507,11.049356,-44.456314,24.887242,1.441174,1.524822,0.118986,0.968201,2.104457,0.843513,32.279876,0.459475,5.015873

### Production data

In [21]:
# Get the subsector total variables
tech_total_vars = [c for c in wide_inputs_outputs_df.columns if "nemomod_entc_annual_production_by_technology" in c]

In [22]:
# Filter to only emission columns avoiding "subsector" total columns
la_production_df = wide_inputs_outputs_df[["primary_id", "time_period"] + tech_total_vars]
la_production_df.head()

,primary_id,time_period,nemomod_entc_annual_production_by_technology_pp_biogas,nemomod_entc_annual_production_by_technology_pp_biomass,nemomod_entc_annual_production_by_technology_pp_coal,nemomod_entc_annual_production_by_technology_pp_coal_ccs,nemomod_entc_annual_production_by_technology_pp_gas,nemomod_entc_annual_production_by_technology_pp_gas_ccs,nemomod_entc_annual_production_by_technology_pp_geothermal,nemomod_entc_annual_production_by_technology_pp_hydropower,nemomod_entc_annual_production_by_technology_pp_nuclear,nemomod_entc_annual_production_by_technology_pp_ocean,nemomod_entc_annual_production_by_technology_pp_oil,nemomod_entc_annual_production_by_technology_pp_solar,nemomod_entc_annual_production_by_technology_pp_waste_incineration,nemomod_entc_annual_production_by_technology_pp_wind,nemomod_entc_annual_production_by_technology_st_batteries,nemomod_entc_annual_production_by_technology_st_compressed_air,nemomod_entc_annual_production_by_technology_st_flywheels,nemomod_entc_annual_production_by_technology_st_pumped_hydro
0,275275,7,0.001232,7.362995,117.672528,0.0,224.240988,0.0,2.403600,65.326059,104.722942,0,5.477464,25.039230,0.346372,58.791354,0.0,0.0,0.0,0.0
1,275275,8,0.001244,6.476040,94.687577,0.0,236.498632,0.0,2.403600,58.432195,103.654598,0,3.831497,28.280866,0.351134,58.791354,0.0,0.0,0.0,0.0
2,275275,9,0.001257,8.429775,178.889484,0.0,187.072926,0.0,2.204133,40.998363,110.792037,0,4.981759,22.155617,0.356193,51.007559,0.0,0.0,0.0,0.0
3,275275,10,0.001270,8.461952,179.572315,0.0,187.786993,0.0,2.212546,41.154856,111.214936,0,5.000775,22.096131,0.361485,51.122144,0.0,0.0,0.0,0.0
4,275275,11,0.001283,8.498595,180.349921,0.0,188.600172,0.0,2.222127,41.333070,111.696533,0,5.022430,25.303084,0.366965,47.990440,0.0,0.0,0.0,0.0

### CB Data

In [18]:
# Make all column names lowercase
cb_df.columns = [c.lower() for c in cb_df.columns]

# Filter to only important cb columns
cb_df = cb_df[["primary_id",
               "future_id",
               "year",
               "technical_cost"]]

cb_df.head()

   primary_id  future_id  year  technical_cost
0      275275          0  2022        0.000000
1      275275          0  2023        0.000000
2      275275          0  2024        0.000000
3      275275          0  2025        1.582723
4      275275          0  2026        8.884747

In [19]:
cb_df.tail()

       primary_id  future_id  year  technical_cost
28560      276275       1000  2046       -0.616939
28561      276275       1000  2047       -0.649769
28562      276275       1000  2048       -0.683128
28563      276275       1000  2049       -0.717001
28564      276275       1000  2050       -0.751297

In [20]:
cb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28565 entries, 0 to 28564
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   primary_id      28565 non-null  int64
 1   future_id       28565 non-null  int64
 2   year            28565 non-null  int64
 3   technical_cost  28565 non-null  float64
dtypes: float64(1), int64(3)
memory usage: 892.8 KB

## Transform time series format into single-row format

### Emission data

In [28]:
# Sum all the subsector emission columns across axis=1
la_emission_total_df = la_emissions_df.copy()
la_emission_total_df["emission_total"] = la_emission_total_df[subsector_total_vars].sum(axis=1)
la_emission_total_df.head()

,primary_id,time_period,emission_co2e_subsector_total_agrc,emission_co2e_subsector_total_ccsq,emission_co2e_subsector_total_entc,emission_co2e_subsector_total_fgtv,emission_co2e_subsector_total_frst,emission_co2e_subsector_total_inen,emission_co2e_subsector_total_ippu,emission_co2e_subsector_total_lndu,emission_co2e_subsector_total_lsmm,emission_co2e_subsector_total_lvst,emission_co2e_subsector_total_scoe,emission_co2e_subsector_total_soil,emission_co2e_subsector_total_trns,emission_co2e_subsector_total_trww,emission_co2e_subsector_total_waso,emission_total
0,275275,7,2.923974,0.0,30.469259,13.094104,-36.545088,117.042622,2.629950,2.050000,0.230319,1.539811,4.491483,1.233181,45.130223,0.447204,3.138402,187.875442
1,275275,8,2.857986,0.0,28.476065,11.929561,-38.817968,114.193574,2.640618,2.057088,0.230824,1.533068,4.525427,1.242080,45.862823,0.454013,3.187628,180.372786
2,275275,9,2.899699,0.0,34.882828,15.633156,-40.622482,113.969034,2.653297,2.064100,0.231385,1.526359,4.561015,1.247478,46.693347,0.461144,3.238212,189.438573
3,275275,10,2.882666,0.0,35.016651,15.680324,-42.118513,112.576725,2.667916,2.071038,0.231985,1.519683,4.598400,1.249169,47.602613,0.468528,3.289838,187.737023
4,275275,11,2.865747,0.0,35.168961,15.736519,-43.406884,111.119217,2.684396,2.077902,0.232615,1.513040,4.637649,1.247322,48.575658,0.476114,3.342286,186.270542

In [29]:
# Keep only the primary_id, time_period, and emission_total columns
la_emission_total_df = la_emission_total_df[["primary_id", "time_period", "emission_total"]]
la_emission_total_df.head()

   primary_id  time_period  emission_total
0      275275            7      187.875442
1      275275            8      180.372786
2      275275            9      189.438573
3      275275           10      187.737023
4      275275           11      186.270542

In [30]:
la_emission_total_df.tail()

       primary_id  time_period  emission_total
28560      275293           31       65.758101
28561      275293           32       63.048681
28562      275293           33       60.471495
28563      275293           34       58.022854
28564      275293           35       56.156181

### Emission data sum

In [31]:
# aggregate data by primary_id summing the emissions
la_emission_df_sum_agg = la_emission_total_df.groupby(["primary_id"]).sum().reset_index()

# Drop time period column
la_emission_df_sum_agg = la_emission_df_sum_agg.drop(columns=["time_period"])
la_emission_df_sum_agg.head()

   primary_id  emission_total
0      275275     1740.787667
1      275276     3318.009812
2      275277     3219.904574
3      275278     2328.191406
4      275279     3225.387997

### Emission data mean

In [32]:
# Filter out rows with time_period < 31
la_filtered_emission_total_df = la_emission_total_df[la_emission_total_df["time_period"] >= 31]
la_filtered_emission_total_df = la_filtered_emission_total_df.reset_index(drop=True)
la_filtered_emission_total_df.head(7)

   primary_id  time_period  emission_total
0      275275           31      -28.417757
1      275275           32      -33.223982
2      275275           33      -37.903236
3      275275           34      -42.511178
4      275275           35      -46.962768
5      275379           31       37.432979
6      275379           32       35.360806

In [33]:
# aggregate data by primary_id by summing the emissions
la_emission_df_mean_agg = la_filtered_emission_total_df.groupby(["primary_id"]).mean().reset_index()

# Rename emission_total to emission_avg_last_five_years
la_emission_df_mean_agg.rename(columns={"emission_total": "emission_avg_last_five_years"}, inplace=True)
la_emission_df_mean_agg

     primary_id  time_period  emission_avg_last_five_years
0        275275         33.0                    -37.803784
1        275276         33.0                     52.248688
2        275277         33.0                     49.914523
3        275278         33.0                     -5.154870
4        275279         33.0                     45.879563
..          ...          ...                           ...
980      276271         33.0                     18.807144
981      276272         33.0                     45.420842
982      276273         33.0                     50.154377
983      276274         33.0                     65.320424
984      276275         33.0                     48.671707

[985 rows x 3 columns]

In [34]:
# Drop year column as it is no longer needed
la_emission_df_mean_agg = la_emission_df_mean_agg.drop(columns=["time_period"])
la_emission_df_mean_agg.head()

   primary_id  emission_avg_last_five_years
0      275275                    -37.803784
1      275276                     52.248688
2      275277                     49.914523
3      275278                     -5.154870
4      275279                     45.879563

### Combining emission agg into one df

In [35]:
print("la_emission_df_mean_agg shape:", la_emission_df_mean_agg.shape)
print("la_emission_df_sum_agg shape:", la_emission_df_sum_agg.shape)

la_emission_df_mean_agg shape: (985, 2)
la_emission_df_sum_agg shape: (985, 2)

In [36]:
la_emissions_df_merged = la_emission_df_mean_agg.merge(la_emission_df_sum_agg, on="primary_id", how="inner")
la_emissions_df_merged.head()

   primary_id  emission_avg_last_five_years  emission_total
0      275275                    -37.803784     1740.787667
1      275276                     52.248688     3318.009812
2      275277                     49.914523     3219.904574
3      275278                     -5.154870     2328.191406
4      275279                     45.879563     3225.387997

In [37]:
print("la_emission_df_mean_agg shape:", la_emission_df_mean_agg.shape)

la_emission_df_mean_agg shape: (985, 2)

### Production data

In [23]:
# Sum all the subsector emission columns across axis=1
la_production_total_df = la_production_df.copy()
la_production_total_df["production_total"] = la_production_total_df[tech_total_vars].sum(axis=1)
la_production_total_df.head()

,primary_id,time_period,nemomod_entc_annual_production_by_technology_pp_biogas,nemomod_entc_annual_production_by_technology_pp_biomass,nemomod_entc_annual_production_by_technology_pp_coal,nemomod_entc_annual_production_by_technology_pp_coal_ccs,nemomod_entc_annual_production_by_technology_pp_gas,nemomod_entc_annual_production_by_technology_pp_gas_ccs,nemomod_entc_annual_production_by_technology_pp_geothermal,nemomod_entc_annual_production_by_technology_pp_hydropower,...,nemomod_entc_annual_production_by_technology_pp_ocean,nemomod_entc_annual_production_by_technology_pp_oil,nemomod_entc_annual_production_by_technology_pp_solar,nemomod_entc_annual_production_by_technology_pp_waste_incineration,nemomod_entc_annual_production_by_technology_pp_wind,nemomod_entc_annual_production_by_technology_st_batteries,nemomod_entc_annual_production_by_technology_st_compressed_air,nemomod_entc_annual_production_by_technology_st_flywheels,nemomod_entc_annual_production_by_technology_st_pumped_hydro,production_total
0,275275,7,0.001232,7.362995,117.672528,0.0,224.240988,0.0,2.403600,65.326059,...,0,5.477464,25.039230,0.346372,58.791354,0.0,0.0,0.0,0.0,611.384764
1,275275,8,0.001244,6.476040,94.687577,0.0,236.498632,0.0,2.403600,58.432195,...,0,3.831497,28.280866,0.351134,58.791354,0.0,0.0,0.0,0.0,593.408737
2,275275,9,0.001257,8.429775,178.889484,0.0,187.072926,0.0,2.204133,40.998363,...,0,4.981759,22.155617,0.356193,51.007559,0.0,0.0,0.0,0.0,606.889103
3,275275,10,0.001270,8.461952,179.572315,0.0,187.786993,0.0,2.212546,41.154856,...,0,5.000775,22.096131,0.361485,51.122144,0.0,0.0,0.0,0.0,608.985405
4,275275,11,0.001283,8.498595,180.349921,0.0,188.600172,0.0,2.222127,41.333070,...,0,5.022430,25.303084,0.366965,47.990440,0.0,0.0,0.0,0.0,611.384619

In [26]:
# Keep only the primary_id, time_period, and emission_total columns
la_production_total_df = la_production_total_df[["primary_id", "time_period", "production_total"]]
la_production_total_df.head()

   primary_id  time_period  production_total
0      275275            7        611.384764
1      275275            8        593.408737
2      275275            9        606.889103
3      275275           10        608.985405
4      275275           11        611.384619

In [27]:
# aggregate data by primary_id summing the emissions
la_production_df_sum_agg = la_production_total_df.groupby(["primary_id"]).sum().reset_index()

# Drop time period column
la_production_df_sum_agg = la_production_df_sum_agg.drop(columns=["time_period"])
la_production_df_sum_agg.head()

   primary_id  production_total
0      275275      16652.046197
1      275276      19378.180701
2      275277      18029.696308
3      275278      18788.752879
4      275279      18792.286140

### CB data

In [38]:
# aggregate data by primary_id and region by summing the technical cost
cb_df_agg = cb_df.groupby(["primary_id", "future_id"]).sum().reset_index()
cb_df_agg

     primary_id  future_id   year  technical_cost
0        275275          0  59044      -33.920729
1        275276          1  59044       -5.143090
2        275277          2  59044       -6.899667
3        275278          3  59044       -7.129115
4        275279          4  59044       -5.769771
..          ...        ...    ...             ...
980      276271        996  59044       -3.788031
981      276272        997  59044       -8.389250
982      276273        998  59044       -8.529192
983      276274        999  59044       -3.336574
984      276275       1000  59044       -8.745369

[985 rows x 4 columns]

In [39]:
# Drop year column as it is no longer needed
cb_df_agg = cb_df_agg.drop(columns=["year"], errors='ignore')
cb_df_agg.head()

   primary_id  future_id  technical_cost
0      275275          0      -33.920729
1      275276          1       -5.143090
2      275277          2       -6.899667
3      275278          3       -7.129115
4      275279          4       -5.769771

In [40]:
cb_df_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   primary_id      985 non-null    int64
 1   future_id       985 non-null    int64
 2   technical_cost  985 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 23.2 KB

## Merge emissions, production and cb data with lhs samples

In [41]:
attr_primary_df = pd.read_csv(os.path.join(SIMULATION_DIR_PATH, "ATTRIBUTE_PRIMARY.csv"))
attr_primary_df

      primary_id  design_id  strategy_id  future_id
0         275275          3         6002          0
1         275276          3         6002          1
2         275277          3         6002          2
3         275278          3         6002          3
4         275279          3         6002          4
...          ...        ...          ...        ...
996       276271          3         6002        996
997       276272          3         6002        997
998       276273          3         6002        998
999       276274          3         6002        999
1000      276275          3         6002       1000

[1001 rows x 4 columns]

In [42]:
la_emission_df_w_future_id = la_emissions_df_merged.merge(attr_primary_df, on="primary_id", how="inner")

# Drop design_id and stratgy_id columns
la_emission_df_w_future_id = la_emission_df_w_future_id.drop(columns=["design_id", "strategy_id"])
la_emission_df_w_future_id

     primary_id  emission_avg_last_five_years  emission_total  future_id
0        275275                    -37.803784     1740.787667          0
1        275276                     52.248688     3318.009812          1
2        275277                     49.914523     3219.904574          2
3        275278                     -5.154870     2328.191406          3
4        275279                     45.879563     3225.387997          4
..          ...                           ...             ...        ...
980      276271                     18.807144     2745.930711        996
981      276272                     45.420842     3260.279374        997
982      276273                     50.154377     3250.844787        998
983      276274                     65.320424     3423.988392        999
984      276275                     48.671707     3236.210012       1000

[985 rows x 4 columns]

In [44]:
la_production_df_w_future_id = la_production_df_sum_agg.merge(attr_primary_df, on="primary_id", how="inner")

# Drop design_id and stratgy_id columns
la_production_df_w_future_id = la_production_df_w_future_id.drop(columns=["design_id", "strategy_id"])
la_production_df_w_future_id

     primary_id  production_total  future_id
0        275275      16652.046197          0
1        275276      19378.180701          1
2        275277      18029.696308          2
3        275278      18788.752879          3
4        275279      18792.286140          4
..          ...               ...        ...
980      276271      19331.017104        996
981      276272      17605.800925        997
982      276273      19603.164647        998
983      276274      17751.256225        999
984      276275      18262.344542       1000

[985 rows x 3 columns]

In [48]:
emission_production_w_future_id=pd.merge(la_production_df_w_future_id, la_emission_df_w_future_id, on=["future_id", "primary_id"], how="inner")

In [49]:
emission_production_w_future_id

,primary_id,production_total,future_id,emission_avg_last_five_years,emission_total
0,275275,16652.046197,0,-37.803784,1740.787667
1,275276,19378.180701,1,52.248688,3318.009812
2,275277,18029.696308,2,49.914523,3219.904574
3,275278,18788.752879,3,-5.154870,2328.191406
4,275279,18792.286140,4,45.879563,3225.387997
...,...,...,...,...,...
980,276271,19331.017104,996,18.807144,2745.930711
981,276272,17605.800925,997,45.420842,3260.279374
982,276273,19603.164647,998,50.154377,3250.844787
983,276274,17751.256225,999,65.320424,3423.988392
984,276275,18262.344542,1000,48.671707,3236.210012

In [ ]:
lhs_trials_df

In [51]:
lhs_emissions_production_merged_df = pd.merge(lhs_trials_df, emission_production_w_future_id, on="future_id", how="inner")
lhs_emissions_production_merged_df.head()

,1,2,3,4,5,6,7,8,9,10,...,1476,1477,1478,1480,1481,future_id,primary_id,production_total,emission_avg_last_five_years,emission_total
0,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,0.490988,0.510280,...,0.005297,0.223598,0.927810,0.036368,0.933822,1,275276,19378.180701,52.248688,3318.009812
1,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,0.779857,0.623335,...,0.784662,0.742266,0.147130,0.081654,0.491202,2,275277,18029.696308,49.914523,3219.904574
2,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,0.884425,0.232722,...,0.950005,0.342632,0.053104,0.316417,0.173655,3,275278,18788.752879,-5.154870,2328.191406
3,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,0.027114,0.532020,...,0.030974,0.912003,0.150989,0.246583,0.353195,4,275279,18792.286140,45.879563,3225.387997
4,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,0.346714,0.892123,...,0.561529,0.611280,0.552761,0.125694,0.147930,5,275280,18030.008356,24.993688,2740.854420

In [52]:
complete_merged_df = pd.merge(lhs_emissions_production_merged_df, cb_df_agg, on=["future_id", "primary_id"], how="inner")
complete_merged_df.head()

,1,2,3,4,5,6,7,8,9,10,...,1477,1478,1480,1481,future_id,primary_id,production_total,emission_avg_last_five_years,emission_total,technical_cost
0,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,0.490988,0.510280,...,0.223598,0.927810,0.036368,0.933822,1,275276,19378.180701,52.248688,3318.009812,-5.143090
1,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,0.779857,0.623335,...,0.742266,0.147130,0.081654,0.491202,2,275277,18029.696308,49.914523,3219.904574,-6.899667
2,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,0.884425,0.232722,...,0.342632,0.053104,0.316417,0.173655,3,275278,18788.752879,-5.154870,2328.191406,-7.129115
3,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,0.027114,0.532020,...,0.912003,0.150989,0.246583,0.353195,4,275279,18792.286140,45.879563,3225.387997,-5.769771
4,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,0.346714,0.892123,...,0.611280,0.552761,0.125694,0.147930,5,275280,18030.008356,24.993688,2740.854420,-8.530492

In [53]:
# rearrange columns to have future_id and primary_id at the front
cols_order = ["future_id", "primary_id"] + [col for col in complete_merged_df.columns if col not in ["future_id", "primary_id"]]
complete_merged_df = complete_merged_df[cols_order]
complete_merged_df

,future_id,primary_id,1,2,3,4,5,6,7,8,...,1475,1476,1477,1478,1480,1481,production_total,emission_avg_last_five_years,emission_total,technical_cost
0,1,275276,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,...,0.364889,0.005297,0.223598,0.927810,0.036368,0.933822,19378.180701,52.248688,3318.009812,-5.143090
1,2,275277,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,...,0.780839,0.784662,0.742266,0.147130,0.081654,0.491202,18029.696308,49.914523,3219.904574,-6.899667
2,3,275278,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,...,0.813845,0.950005,0.342632,0.053104,0.316417,0.173655,18788.752879,-5.154870,2328.191406,-7.129115
3,4,275279,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,...,0.911838,0.030974,0.912003,0.150989,0.246583,0.353195,18792.286140,45.879563,3225.387997,-5.769771
4,5,275280,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,...,0.927056,0.561529,0.611280,0.552761,0.125694,0.147930,18030.008356,24.993688,2740.854420,-8.530492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,996,276271,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,...,0.045121,0.790492,0.081530,0.351688,0.746613,0.853002,19331.017104,18.807144,2745.930711,-3.788031
980,997,276272,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,...,0.079728,0.918024,0.653280,0.161674,0.033243,0.257661,17605.800925,45.420842,3260.279374,-8.389250
981,998,276273,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,...,0.603350,0.377625,0.316224,0.615736,0.996441,0.704642,19603.164647,50.154377,3250.844787,-8.529192
982,999,276274,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,...,0.168413,0.611178,0.295950,0.813797,0.934377,0.473035,17751.256225,65.320424,3423.988392,-3.336574
983,1000,276275,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,...,0.965431,0.352193,0.278569,0.164544,0.144563,0.306248,18262.344542,48.671707,3236.210012,-8.745369

In [54]:
var_traj_df = pd.read_csv(os.path.join(MAPPING_DIR_PATH, "var_trajgroups_experiment.csv"))
var_traj_df.tail(10)

    variable_trajectory_group
37                         38
38                         39
39                         40
40                         41
41                         42
42                         43
43                         44
44                         45
45                         46
46                         47

In [55]:
# Convert the variable_trajectory_group column to list of strings
relevant_lhs_cols = var_traj_df["variable_trajectory_group"].values
relevant_lhs_cols = [str(col) for col in relevant_lhs_cols.tolist()]
# relevant_lhs_cols

In [56]:
df_cols = complete_merged_df.columns.tolist()

# Filter the relevant_lhs_cols to only include those that are in df_cols
relevant_lhs_cols = [col for col in relevant_lhs_cols if col in df_cols]

In [57]:
# filter complete_merged_df to keep only relevant columns
cols_to_keep = ["future_id", "primary_id"] + list(relevant_lhs_cols) + ["emission_avg_last_five_years", "emission_total", "production_total","technical_cost"]
merged_df_filtered = complete_merged_df[cols_to_keep]

In [58]:
merged_df_filtered

,future_id,primary_id,1,2,3,4,5,6,7,8,...,42,43,44,45,46,47,emission_avg_last_five_years,emission_total,production_total,technical_cost
0,1,275276,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,...,0.053597,0.175103,0.379422,0.438093,0.149362,0.869757,52.248688,3318.009812,19378.180701,-5.143090
1,2,275277,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,...,0.246165,0.101025,0.717013,0.368791,0.774941,0.483352,49.914523,3219.904574,18029.696308,-6.899667
2,3,275278,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,...,0.122444,0.653845,0.216259,0.714853,0.881270,0.581230,-5.154870,2328.191406,18788.752879,-7.129115
3,4,275279,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,...,0.592915,0.564895,0.027725,0.138890,0.820709,0.250616,45.879563,3225.387997,18792.286140,-5.769771
4,5,275280,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,...,0.432240,0.662820,0.179231,0.631375,0.395960,0.661637,24.993688,2740.854420,18030.008356,-8.530492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,996,276271,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,...,0.567859,0.873065,0.309462,0.213959,0.531121,0.413153,18.807144,2745.930711,19331.017104,-3.788031
980,997,276272,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,...,0.356410,0.584330,0.195851,0.217361,0.920388,0.402516,45.420842,3260.279374,17605.800925,-8.389250
981,998,276273,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,...,0.653782,0.429175,0.977175,0.914779,0.307569,0.506892,50.154377,3250.844787,19603.164647,-8.529192
982,999,276274,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,...,0.826523,0.961181,0.882943,0.900195,0.448056,0.664405,65.320424,3423.988392,17751.256225,-3.336574
983,1000,276275,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,...,0.936939,0.657785,0.017582,0.513939,0.232670,0.118241,48.671707,3236.210012,18262.344542,-8.745369

In [59]:
print("Merged DataFrame shape:", merged_df_filtered.shape) #NOTE: We lost 1 row because future_id 0 is not in the lhs_trials_df

Merged DataFrame shape: (984, 52)

## Add variable names to lhs columns

In [60]:
var_specifications_df = pd.read_csv(os.path.join(MAPPING_DIR_PATH, "variable_specification_to_sample_group.csv"))
# Filter var_specifications_df by sample_group in relevant_lhs_cols
relevant_lhs_cols = [int(col) for col in relevant_lhs_cols]
var_specifications_df = var_specifications_df[var_specifications_df["sample_group"].isin(relevant_lhs_cols)]
var_specifications_df = var_specifications_df.sort_values(by="sample_group", ascending=True)

In [61]:
def process_variable_prefix(df):
    result = []
    for group, group_df in df.groupby('sample_group'):
        variables = group_df['variable_specification'].tolist()
        if len(variables) == 1:
            prefix = variables[0]
        else:
            prefix = os.path.commonprefix(variables)
            # Clean trailing underscores
            prefix = prefix.rstrip('_')
            
        prefix = f"group_{group}_{prefix}"
        result.append({'sample_group': group, 'variable_prefix': prefix})
    return pd.DataFrame(result)

prefix_df = process_variable_prefix(var_specifications_df)
prefix_df

    sample_group                                    variable_prefix
0              1                            group_1_ef_lvst_entferm
1              2                                    group_2_yf_agrc
2              3                             group_3_demscalar_soil
3              4                             group_4_demscalar_ippu
4              5    group_5_efficfactor_enfu_industrial_energy_fuel
5              6                    group_6_elecfuelefficiency_trns
6              7   group_7_factor_waso_waste_per_capita_scalar_food
7              8                                  group_8_frac_fgtv
8              9      group_9_frac_agrc_agriculture_production_lost
9             10                                 group_10_frac_agrc
10            12  group_12_frac_enfu_transmission_loss_fuel_elec...
11            13                                          group_13_
12            14                  group_14_frac_ippu_cement_clinker
13            15     group_15_frac_ippu_production_with_co2_capture
14            16                              group_16_frac_lvst_mm
15            17                         group_17_frac_trns_fuelmix
16            18                group_18_frac_trns_mtkm_dem_freight
17            19                         group_19_frac_trns_pkm_dem
18            20                              group_20_frac_wali_ww
19            21                    group_21_frac_waso_non_recycled
20            22                                 group_22_frac_waso
21            23                        group_23_frac_waso_recycled
22            24                                 group_24_frac_waso
23            25                          group_25_frac_inen_energy
24            26                          group_26_frac_inen_energy
25            27                     group_27_frac_scoe_heat_energy
26            28                       group_28_fuelefficiency_trns
27            29                                     group_29_gasrf
28            30                             group_30_ef_ippu_tonne
29            31                     group_31_ef_ippu_tonne_n2o_per
30            32                  group_32_lndu_reallocation_factor
31            33                              group_33_exports_lvst
32            34                                group_34_nemomod_en
33            35  group_35_occrate_trns_passenger_per_vehicle_ro...
34            36                     group_36_pij_lndu_croplands_to
35            37             group_37_pij_lndu_forests_mangroves_to
36            38               group_38_pij_lndu_forests_primary_to
37            39             group_39_pij_lndu_forests_secondary_to
38            40                                          group_40_
39            41                         group_41_pij_lndu_other_to
40            42                   group_42_pij_lndu_settlements_to
41            43                      group_43_pij_lndu_wetlands_to
42            44       group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha
43            45             group_45_scalar_lvst_carrying_capacity
44            46       group_46_scalar_scoe_appliance_energy_demand
45            47            group_47_scalar_scoe_heat_energy_demand

In [62]:
var_specifications_df[var_specifications_df["sample_group"].isin([13, 40])]

                           variable_specification  sample_group
560   elasticity_agrc_sugar_cane_demand_to_income            13
876                     frac_gnrl_eating_red_meat            13
1177      frac_lndu_proportion_grasslands_pasture            40
2020       pij_lndu_grasslands_to_forests_primary            40
2021     pij_lndu_grasslands_to_forests_secondary            40
2022            pij_lndu_grasslands_to_grasslands            40
2024           pij_lndu_grasslands_to_settlements            40
2025              pij_lndu_grasslands_to_wetlands            40
2023                 pij_lndu_grasslands_to_other            40
2019     pij_lndu_grasslands_to_forests_mangroves            40
2018             pij_lndu_grasslands_to_croplands            40

In [63]:
prefix_df.loc[prefix_df["sample_group"] == 13, "variable_prefix"] = "group_13_frac_gnrl_eating_red_meats+"
prefix_df.loc[prefix_df["sample_group"] == 40, "variable_prefix"] = "group_40_pij_lndu_grasslands+"

prefix_df = prefix_df.sort_values(by="variable_prefix", ascending=True)
prefix_df

    sample_group                                    variable_prefix
9             10                                 group_10_frac_agrc
10            12  group_12_frac_enfu_transmission_loss_fuel_elec...
11            13               group_13_frac_gnrl_eating_red_meats+
12            14                  group_14_frac_ippu_cement_clinker
13            15     group_15_frac_ippu_production_with_co2_capture
14            16                              group_16_frac_lvst_mm
15            17                         group_17_frac_trns_fuelmix
16            18                group_18_frac_trns_mtkm_dem_freight
17            19                         group_19_frac_trns_pkm_dem
0              1                            group_1_ef_lvst_entferm
18            20                              group_20_frac_wali_ww
19            21                    group_21_frac_waso_non_recycled
20            22                                 group_22_frac_waso
21            23                        group_23_frac_waso_recycled
22            24                                 group_24_frac_waso
23            25                          group_25_frac_inen_energy
24            26                          group_26_frac_inen_energy
25            27                     group_27_frac_scoe_heat_energy
26            28                       group_28_fuelefficiency_trns
27            29                                     group_29_gasrf
1              2                                    group_2_yf_agrc
28            30                             group_30_ef_ippu_tonne
29            31                     group_31_ef_ippu_tonne_n2o_per
30            32                  group_32_lndu_reallocation_factor
31            33                              group_33_exports_lvst
32            34                                group_34_nemomod_en
33            35  group_35_occrate_trns_passenger_per_vehicle_ro...
34            36                     group_36_pij_lndu_croplands_to
35            37             group_37_pij_lndu_forests_mangroves_to
36            38               group_38_pij_lndu_forests_primary_to
37            39             group_39_pij_lndu_forests_secondary_to
2              3                             group_3_demscalar_soil
38            40                      group_40_pij_lndu_grasslands+
39            41                         group_41_pij_lndu_other_to
40            42                   group_42_pij_lndu_settlements_to
41            43                      group_43_pij_lndu_wetlands_to
42            44       group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha
43            45             group_45_scalar_lvst_carrying_capacity
44            46       group_46_scalar_scoe_appliance_energy_demand
45            47            group_47_scalar_scoe_heat_energy_demand
3              4                             group_4_demscalar_ippu
4              5    group_5_efficfactor_enfu_industrial_energy_fuel
5              6                    group_6_elecfuelefficiency_trns
6              7   group_7_factor_waso_waste_per_capita_scalar_food
7              8                                  group_8_frac_fgtv
8              9      group_9_frac_agrc_agriculture_production_lost

In [64]:
# Let's use the prefix_df to rename the columns in merged_df_filtered
def rename_columns_with_prefix(merged_df, prefix_df):
    df = merged_df.copy()
    for _, row in prefix_df.iterrows():
        sample_group = row['sample_group']
        variable_prefix = row['variable_prefix']
        cols_to_rename = [col for col in df.columns if col.startswith(str(sample_group))]
        for col in cols_to_rename:
            new_col_name = f"{variable_prefix}"
            df = df.rename(columns={col: new_col_name})
    return df
merged_df_filtered_w_prefix = rename_columns_with_prefix(merged_df_filtered, prefix_df)

In [65]:
merged_df_filtered_w_prefix

,future_id,primary_id,group_1_ef_lvst_entferm,group_2_yf_agrc,group_3_demscalar_soil,group_4_demscalar_ippu,group_5_efficfactor_enfu_industrial_energy_fuel,group_6_elecfuelefficiency_trns,group_7_factor_waso_waste_per_capita_scalar_food,group_8_frac_fgtv,...,group_42_pij_lndu_settlements_to,group_43_pij_lndu_wetlands_to,group_44_ef_agrc_anaerobicdom_rice_kg_ch4_ha,group_45_scalar_lvst_carrying_capacity,group_46_scalar_scoe_appliance_energy_demand,group_47_scalar_scoe_heat_energy_demand,emission_avg_last_five_years,emission_total,production_total,technical_cost
0,1,275276,0.952436,0.360397,0.202990,0.995748,0.369859,0.919920,0.478450,0.445798,...,0.053597,0.175103,0.379422,0.438093,0.149362,0.869757,52.248688,3318.009812,19378.180701,-5.143090
1,2,275277,0.304955,0.204875,0.540658,0.800192,0.206396,0.777352,0.805727,0.536048,...,0.246165,0.101025,0.717013,0.368791,0.774941,0.483352,49.914523,3219.904574,18029.696308,-6.899667
2,3,275278,0.609262,0.366443,0.601808,0.916668,0.386475,0.181162,0.138910,0.768925,...,0.122444,0.653845,0.216259,0.714853,0.881270,0.581230,-5.154870,2328.191406,18788.752879,-7.129115
3,4,275279,0.815313,0.487444,0.323954,0.634299,0.064625,0.926815,0.633805,0.439346,...,0.592915,0.564895,0.027725,0.138890,0.820709,0.250616,45.879563,3225.387997,18792.286140,-5.769771
4,5,275280,0.973878,0.842718,0.884382,0.483039,0.455502,0.003343,0.571994,0.108021,...,0.432240,0.662820,0.179231,0.631375,0.395960,0.661637,24.993688,2740.854420,18030.008356,-8.530492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,996,276271,0.218189,0.886941,0.569155,0.107766,0.955775,0.380014,0.569711,0.312233,...,0.567859,0.873065,0.309462,0.213959,0.531121,0.413153,18.807144,2745.930711,19331.017104,-3.788031
980,997,276272,0.510025,0.235856,0.847465,0.138888,0.182086,0.453749,0.242018,0.215693,...,0.356410,0.584330,0.195851,0.217361,0.920388,0.402516,45.420842,3260.279374,17605.800925,-8.389250
981,998,276273,0.276479,0.612911,0.642697,0.952037,0.176638,0.411246,0.169671,0.694365,...,0.653782,0.429175,0.977175,0.914779,0.307569,0.506892,50.154377,3250.844787,19603.164647,-8.529192
982,999,276274,0.600573,0.553323,0.306380,0.464389,0.834916,0.786519,0.717580,0.168263,...,0.826523,0.961181,0.882943,0.900195,0.448056,0.664405,65.320424,3423.988392,17751.256225,-3.336574
983,1000,276275,0.164542,0.057579,0.648085,0.210240,0.441924,0.364614,0.031031,0.873487,...,0.936939,0.657785,0.017582,0.513939,0.232670,0.118241,48.671707,3236.210012,18262.344542,-8.745369

In [66]:
#save the merged DataFrame to a CSV file
merged_df_filtered_w_prefix.to_csv(os.path.join(TRAINING_DIR_PATH, "training_data_v4.1_narrative_profiles.csv"), index=False)