In [20]:
import pandas as pd
import os

In [21]:
# Set up paths
SCRIPT_DIR_PATH = os.getcwd()
CW_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "cw")
DATA_DIR_PATH = os.path.join(SCRIPT_DIR_PATH, "data")
ENSEMBLE_DIR_PATH = os.path.join(DATA_DIR_PATH, "ensemble_data")
run_id = "2025-09-18t09;19;22.726476"
RUN_DIR_PATH = os.path.join(ENSEMBLE_DIR_PATH, f"sisepuede_summary_results_run_sisepuede_run_{run_id}")

In [23]:
cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"cba_la_{run_id}_tornado.csv"))
# cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_{run_id}.csv"))
cb_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,AGRC:DEC_CH4_RICE,0.0,louisiana,7.0,pop_unimproved_rural,299091.209054,299091.209054,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,AGRC:DEC_CH4_RICE,0.0,louisiana,8.0,pop_unimproved_rural,294340.078493,294340.078493,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,AGRC:DEC_CH4_RICE,0.0,louisiana,9.0,pop_unimproved_rural,289474.711388,289474.711388,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,AGRC:DEC_CH4_RICE,0.0,louisiana,10.0,pop_unimproved_rural,284494.629299,284494.629299,0.0,cb:wali:technical_cost:sanitation:unimp_rural,-0.0
4,AGRC:DEC_CH4_RICE,0.0,louisiana,11.0,pop_unimproved_rural,279403.968085,279403.968085,0.0,cb:wali:technical_cost:sanitation:unimp_rural,-0.0

In [24]:
#print shape
cb_df.shape

(401056, 10)

In [25]:
cb_df.future_id.nunique()

1

In [26]:
# evaluate each column null values
null_counts = cb_df.isnull().sum()
print("Null values in each column:")
print(null_counts)

Null values in each column:
strategy_code                0
future_id                    0
region                       0
time_period                  0
difference_variable          0
variable_value_baseline    900
variable_value_pathway       0
difference_value           900
variable                     0
value                      828
dtype: int64

In [27]:
null_baseline = cb_df[cb_df['variable_value_baseline'].isnull()]
null_baseline

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
353992,FGTV:DEC_LEAKS,0.0,louisiana,25.0,energy_demand_enfu_total_fuel_coal,NaN,1.431869,NaN,cb:fgtv:technical_cost:leaks:X,NaN
353993,FGTV:DEC_LEAKS,0.0,louisiana,26.0,energy_demand_enfu_total_fuel_coal,NaN,1.580035,NaN,cb:fgtv:technical_cost:leaks:X,NaN
353994,FGTV:DEC_LEAKS,0.0,louisiana,27.0,energy_demand_enfu_total_fuel_coal,NaN,1.581415,NaN,cb:fgtv:technical_cost:leaks:X,NaN
353995,FGTV:DEC_LEAKS,0.0,louisiana,28.0,energy_demand_enfu_total_fuel_coal,NaN,1.582892,NaN,cb:fgtv:technical_cost:leaks:X,NaN
353996,FGTV:DEC_LEAKS,0.0,louisiana,29.0,energy_demand_enfu_total_fuel_coal,NaN,1.584469,NaN,cb:fgtv:technical_cost:leaks:X,NaN
...,...,...,...,...,...,...,...,...,...,...
400838,PFLO:TWI_FULL_LEAP_SET_LC,0.0,louisiana,18.0,energy_demand_enfu_total_fuel_natural_gas,NaN,11.077888,NaN,cb:fgtv:technical_cost:leaks:X_shifted2023.0,NaN
400839,PFLO:TWI_FULL_LEAP_SET_LC,0.0,louisiana,19.0,energy_demand_enfu_total_fuel_natural_gas,NaN,11.038033,NaN,cb:fgtv:technical_cost:leaks:X_shifted2024.0,NaN
400840,PFLO:TWI_FULL_LEAP_SET_LC,0.0,louisiana,17.0,energy_demand_enfu_total_fuel_oil,NaN,2.010499,NaN,cb:fgtv:technical_cost:leaks:X_shifted2022.0,NaN
400841,PFLO:TWI_FULL_LEAP_SET_LC,0.0,louisiana,18.0,energy_demand_enfu_total_fuel_oil,NaN,1.968529,NaN,cb:fgtv:technical_cost:leaks:X_shifted2023.0,NaN
400842,PFLO:TWI_FULL_LEAP_SET_LC,0.0,louisiana,19.0,energy_demand_enfu_total_fuel_oil,NaN,1.936145,NaN,cb:fgtv:technical_cost:leaks:X_shifted2024.0,NaN

In [28]:
null_baseline.variable.unique()  # Check unique future_ids with null baseline values

array(['cb:fgtv:technical_cost:leaks:X',
       'cb:fgtv:technical_cost:flaring:X',
       'cb:fgtv:technical_cost:leaks:X_shifted2022.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2023.0',
       'cb:fgtv:technical_cost:leaks:X_shifted2024.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2022.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2023.0',
       'cb:fgtv:technical_cost:flaring:X_shifted2024.0'], dtype=object)

In [29]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
dtype: int64

In [30]:
# check the rows with -inf values in 'value' column
negative_inf_rows = cb_df[cb_df['value'] == -float('inf')]
print("Rows with -inf in 'value' column:")
negative_inf_rows

Rows with -inf in 'value' column:

Empty DataFrame
Columns: [strategy_code, future_id, region, time_period, difference_variable, variable_value_baseline, variable_value_pathway, difference_value, variable, value]
Index: []

In [31]:
# # replace -inf with 0 in 'value' column
# cb_df['value'] = cb_df['value'].replace(-float('inf'), 0)
# cb_df['difference_value'] = cb_df['difference_value'].replace(-float('inf'), 0)

In [32]:
# Check for -inf values in numeric columns
negative_inf_counts = (cb_df == -float('inf')).sum()
print("Negative infinity counts in each column:")
print(negative_inf_counts)

Negative infinity counts in each column:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
dtype: int64

In [33]:
# replace all nans with 0
cb_df.fillna(0, inplace=True)
# Check if there are still any null values
null_counts_after_fill = cb_df.isnull().sum()
print("Null values after fillna:")
print(null_counts_after_fill)

Null values after fillna:
strategy_code              0
future_id                  0
region                     0
time_period                0
difference_variable        0
variable_value_baseline    0
variable_value_pathway     0
difference_value           0
variable                   0
value                      0
dtype: int64

In [34]:
cb_df.future_id.nunique()

1

In [35]:
# Save updated DataFrame
cb_df.to_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_updated_{run_id}_tornado.csv"), index=False)
print(f"Updated DataFrame saved to combined_cb_results_updated_{run_id}.csv")

Updated DataFrame saved to combined_cb_results_updated_2025-09-18t09;19;22.726476.csv

### Quick Validation

In [40]:
saved_df = pd.read_csv(os.path.join(RUN_DIR_PATH, f"combined_cb_results_updated_{run_id}_tornado.csv"))
saved_df.head()

,strategy_code,future_id,region,time_period,difference_variable,variable_value_baseline,variable_value_pathway,difference_value,variable,value
0,AGRC:DEC_CH4_RICE,0.0,louisiana,7.0,pop_unimproved_rural,299091.209054,299091.209054,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
1,AGRC:DEC_CH4_RICE,0.0,louisiana,8.0,pop_unimproved_rural,294340.078493,294340.078493,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
2,AGRC:DEC_CH4_RICE,0.0,louisiana,9.0,pop_unimproved_rural,289474.711388,289474.711388,0.0,cb:wali:technical_cost:sanitation:unimp_rural,0.0
3,AGRC:DEC_CH4_RICE,0.0,louisiana,10.0,pop_unimproved_rural,284494.629299,284494.629299,0.0,cb:wali:technical_cost:sanitation:unimp_rural,-0.0
4,AGRC:DEC_CH4_RICE,0.0,louisiana,11.0,pop_unimproved_rural,279403.968085,279403.968085,0.0,cb:wali:technical_cost:sanitation:unimp_rural,-0.0

In [41]:
print(cb_df.shape)
print(saved_df.shape)

(401056, 10)
(401056, 10)

In [42]:
saved_df.future_id.nunique()

1

In [43]:
saved_df.primary_id.nunique()

AttributeError: 'DataFrame' object has no attribute 'primary_id'

## Check wide file

In [19]:
wide_cb_df = pd.read_csv(os.path.join(RUN_DIR_PATH, "wide_cb_data_lhc_2025-08-28t15;29;22.344855.csv"))
wide_cb_df.head()

,primary_id,future_id,strategy_code,Year,air_pollution,congestion,consumer_savings,crop_value,ecosystem_services,env_pollution,...,human_health,ippu_value,land_pollution,lvst_value,road_safety,sector_specific,system_cost,technical_cost,technical_savings,water_pollution
0,402402,1,PFLO:ALL_LA_ACTIONS,2022.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
1,402402,1,PFLO:ALL_LA_ACTIONS,2023.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
2,402402,1,PFLO:ALL_LA_ACTIONS,2024.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.0,...,0.000000,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
3,402402,1,PFLO:ALL_LA_ACTIONS,2025.0,9.695006e-16,-1.451481e-23,0.021749,0.000000e+00,6.959355e-12,0.0,...,0.019772,0.0,0.000000e+00,0.0,-2.494771e-23,5.093170e-14,0.000000e+00,-0.021329,0.000000e+00,0.0
4,402402,1,PFLO:ALL_LA_ACTIONS,2026.0,1.425974e-16,0.000000e+00,0.043782,2.673078e-14,7.691665e-12,0.0,...,0.039802,0.0,-5.968559e-17,0.0,0.000000e+00,-5.563550e-14,-5.269051e-15,-0.072557,8.114148e-17,0.0

In [20]:
# check for null values in wide file
wide_null_counts = wide_cb_df.isnull().sum()
print("Null values in wide DataFrame:")
print(wide_null_counts)

Null values in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64

In [21]:
# check for inf and -inf values in wide file
wide_negative_inf_counts = (wide_cb_df == -float('inf')).sum()
print("Negative infinity counts in wide DataFrame:")
print(wide_negative_inf_counts)

Negative infinity counts in wide DataFrame:
primary_id            0
future_id             0
strategy_code         0
Year                  0
air_pollution         0
congestion            0
consumer_savings      0
crop_value            0
ecosystem_services    0
env_pollution         0
fuel_cost             0
human_health          0
ippu_value            0
land_pollution        0
lvst_value            0
road_safety           0
sector_specific       0
system_cost           0
technical_cost        0
technical_savings     0
water_pollution       0
dtype: int64

In [22]:
wide_cb_df.future_id.nunique()

991